### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by dckiller51** [tesneddon/wxWmr500#4]
Hello, Does it still work for you? I can't connect to the smart live wmr500 app. Firmware 1.4.7.6

If I understand correctly, you need at least one access here ?
http://web-wmr500.idtlive.com/index/service/login.html
In France a store sells this station 25€.

**Comment by tesneddon** [comment]
Hi,

Yes, this module still works. You can see my own weather station site at http://fw9238.cmkrnl.io 

It has been down for a few days as I have been too busy dealing with other things to fix it up. The real problem is configuring a local DNS and mqtt server.

I will have to write some detail in the wiki. I should have some time to write it up over the weekend. Most of it is already done, I just haven't got round to publishing it yet.

One thing to remember though is that these constantly drop out. It's so bad that I have it connected to an IKEA zigbee power plug. I then run a cron job every 10 minutes to reset the device so that it does not get wedged.

I'll updated the issue when I have published some details to the wiki, so watch this space.

Regards, Tim.

**Comment by dckiller51** [comment]
Awesome. Thanks for your feedback. But you need access to this site http://web-wmr500.idtlive.com/index/service/login.html.
What app did you take for the first integration on your phone? To date we can create an account but each time it tells me network failure and asks to do the pairing again while the box is well connected to the network I see it on my router.

**Comment by dckiller51** [comment]
https://github.com/tesneddon/wxWmr500/issues/5#issuecomment-927340506

![Screenshot_2021-09-28-08-56-20-563_com android chrome](https://user-images.githubusercontent.com/53062806/135039448-a33c3e7b-afc6-4577-a1fa-36698ceabf6e.jpg)

**Comment by tesneddon** [comment]
Really glad to see that you got this up and working, @dckiller51!

**Comment by bpk35** [comment]
Hi,

I am looking for solutions to recover weather data since the site http://web-wmr500.idtlive.com is stopped.
Which DNS server and which broker do you use under Windows?
Do you have an example configuration?

**Comment by tesneddon** [comment]
Hi @bpk35,

I run my set up on a Raspian system, so I do not use Windows at all. The DNS server I use is dnsmasq. For the MQTT broker, I use mosquitto.

**Comment by Puy-Robin** [comment]
Hi Guy,
Some of you seem to have the WMR500 working well- I can't even get the makers phone app working. Can you please share how you are able to have it work so well, I would like to publish my local weather on my website if it is possible.

kind regards

**Comment by pololesgazs** [comment]
Hi @tesneddon, 

I bought this weather station and I wanted to retrieve data even if the app is not working anymore. 
Can you detail how you make your installation? Thanks!
Regards, 

Paul
